# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Auth_sprint_2/v1/auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Auth_sprint_2/v1/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Auth_sprint_2.v1 import request_context_pb2 as Auth__sprint__2_dot_v1_dot_request__context__pb2
from Auth_sprint_2.v1 import errors_pb2 as Auth__sprint__2_dot_v1_dot_errors__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x41uth_sprint_2/v1/auth.proto\x12\x10\x61uth_sprint_2.v1\x1a&Auth_sprint_2/v1/request_context.proto\x1a\x1d\x41uth_sprint_2/v1/errors.proto\"]\n\x12VerifyTokenRequest\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x31\n\x07\x63ontext\x18\x02 \x01(\x0b\x32 .auth_sprint_2.v1.RequestContext\"D\n\x0cUserIdentity\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05roles\x18\x02 \x03(\t\x12\x14\n\x0cis_superuser\x18\x03 \x01(\x08\"y\n\x13VerifyTokenResponse\x12.\n\x04user\x18\x01 \x01(\x0b\x32\x1e.auth_sprint_2.v1.UserIdentityH\x00\x12(\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x17.auth_sprint_2.v1.ErrorH\x00\x42\x08\n\x06result2i\n\x0b\x41uthService\x12Z\n\x0bVerifyToken\x12$.auth_sprint_2.v1.VerifyTokenRequest\x1a%.auth_sprint_2.v1.VerifyTokenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Auth_sprint_2.v1.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERIFYTOKENREQUEST']._serialized_start=120
  _globals['_VERIFYTOKENREQUEST']._serialized_end=213
  _globals['_USERIDENTITY']._serialized_start=215
  _globals['_USERIDENTITY']._serialized_end=283
  _globals['_VERIFYTOKENRESPONSE']._serialized_start=285
  _globals['_VERIFYTOKENRESPONSE']._serialized_end=406
  _globals['_AUTHSERVICE']._serialized_start=408
  _globals['_AUTHSERVICE']._serialized_end=513
# @@protoc_insertion_point(module_scope)
