# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Auth_sprint_2/v1/errors.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Auth_sprint_2/v1/errors.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x41uth_sprint_2/v1/errors.proto\x12\x10\x61uth_sprint_2.v1\"C\n\x05\x45rror\x12)\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x1b.auth_sprint_2.v1.ErrorCode\x12\x0f\n\x07message\x18\x02 \x01(\t*\xb8\x01\n\tErrorCode\x12\x1a\n\x16\x45RROR_CODE_UNSPECIFIED\x10\x00\x12\x11\n\rTOKEN_INVALID\x10\x01\x12\x11\n\rTOKEN_EXPIRED\x10\x02\x12\x15\n\x11TOKEN_BLACKLISTED\x10\x03\x12\x14\n\x10TOKEN_IS_REFRESH\x10\x04\x12\x15\n\x11PERMISSION_DENIED\x10\x05\x12\x12\n\x0eUSER_NOT_FOUND\x10\x06\x12\x11\n\rUSER_INACTIVE\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Auth_sprint_2.v1.errors_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ERRORCODE']._serialized_start=121
  _globals['_ERRORCODE']._serialized_end=305
  _globals['_ERROR']._serialized_start=51
  _globals['_ERROR']._serialized_end=118
# @@protoc_insertion_point(module_scope)
